### ISSUE TITLE
Autofoucs is not working

### ISSUE THREAD

**Issue by PradeepLinkites** [naveenvignesh5/react-native-otp-textinput#16]
Autofoucs is not working correct. it is showing in last cell.
![Screenshot 2021-08-12 at 5 38 01 PM](https://user-images.githubusercontent.com/47211749/129194154-e32bfa6a-4123-4753-a917-38d36986094b.png)

**Comment by devilop** [comment]
Index.js (Modify)

TextInputs.push(
        <TextInput
          ref={(e) => {
            this.inputs[i] = e;
          }}
          key={i}
          autoCorrect={false}
          keyboardType={keyboardType}
          autoFocus={i==0?true:false}
          value={otpText[i] || ''}
          style={inputStyle}
          maxLength={this.props.inputCellLength}
          onFocus={() => this.onInputFocus(i)}
          onChangeText={(text) => this.onTextChange(text, i)}
          multiline={false}
          onKeyPress={(e) => this.onKeyPress(e, i)}
          {...textInputProps}
        />
      );

**Comment by naveenvignesh5** [comment]
Latest release contains fix for this, so closing this.
