### ISSUE TITLE
How can we open text keyboard instated of number pad?

### ISSUE THREAD

**Issue by avinashjgtp10** [naveenvignesh5/react-native-otp-textinput#17]
in the below screen, I have integrated OTP  but I am getting numbers and text for ex. 12bc 
![Screen Shot 2021-10-02 at 4 36 05 PM](https://user-images.githubusercontent.com/25630955/135713510-ee834f64-598e-4fac-9be0-4affb5303a77.png)

**Comment by naveenvignesh5** [comment]
Closing this issue. @zed-shawn's answer is the solution to this bug.
