### ISSUE TITLE
offTintColor for particular input filed

### ISSUE THREAD

**Issue by Ramaraju1992** [naveenvignesh5/react-native-otp-textinput#19]
Hi Team,
As per our requirement we need to set **_offTintColor_** for particular **TextInput** filed on entered status.
We need to differentiate cells which are filled with OTP, but now all fields sets same border color.

![image](https://user-images.githubusercontent.com/31759293/143257852-f7ac4c24-76d0-4cb7-9ae5-2736776dffda.png)

**Comment by naveenvignesh5** [comment]
Will look into this enhancement for the next release. Thanks for your input.

**Comment by naveenvignesh5** [comment]
Enhancement done and pushed to `v1.0.0`. Kindly check and give your feedbacks. Thanks.
