### ISSUE TITLE
Return value on handleTextChange function missing last character

### ISSUE THREAD

**Issue by TrungQNguyen** [naveenvignesh5/react-native-otp-textinput#2]
Return value on handleTextChange function missing last character

Problem is onTextChange function

My solution is move this code 

> handleTextChange(this.state.otpText.join(""));

inside like this

> this.setState((prevState) => {
>             let { otpText } = prevState;
>             otpText[i] = text;
>             handleTextChange(this.state.otpText.join(""));
>             return {
>                 otpText,
>             }
> });

**Comment by naveenvignesh5** [comment]
Fixed in latest release.
