### ISSUE TITLE
On press back delete button input is not working again

### ISSUE THREAD

**Issue by sohanpc** [naveenvignesh5/react-native-otp-textinput#21]
Hi,

When entering an OTP code, if the user clicks the back button, it's as though there is an extra digit. If the user tries to enter another number, the curser stays in the box prior and will not go to the next box. I have created a screencast for you

https://user-images.githubusercontent.com/34681057/164624776-9512fa9f-04f2-41fc-9f4a-d81e167bc88c.mov

**Comment by itxchandan** [comment]
I have the same Issue.

**Comment by naveenvignesh5** [comment]
This issue has been addressed in the latest release. @sohanpc could you check and close this issue ?

**Comment by naveenvignesh5** [comment]
Closing this issue as there is no response. Kindly reopen if the same issue reappears.
