### ISSUE TITLE
Add typescript support

### ISSUE THREAD

**Issue by anubhav-sl** [naveenvignesh5/react-native-otp-textinput#22]
Getting this error : `Could not find a declaration file for module 'react-native-otp-textinput'. 'C:/Users/Anubhav/booknav-frontend/node_modules/react-native-otp-textinput/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-native-otp-textinput` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-otp-textinput';`ts(7016)`

**Comment by chunkomac** [comment]
There seem to be some typings but they are not linked in package.json. I manually added that but still it doesnt work.

**Comment by lylysunshinee** [comment]
workaround with add 
 /* @ts-ignore */

**Comment by naveenvignesh5** [comment]
Have added typescript support with latest release **v1.1.0**. Closing this issue.
