### ISSUE TITLE
Paste doesn't fill the entire opt fields, only the first field

### ISSUE THREAD

**Issue by benjamineruvieru** [naveenvignesh5/react-native-otp-textinput#32]
The title says it all

If I copy an opt eg "475939"
And long press on the first input field
<img width="268" alt="Screenshot 2023-01-27 at 9 32 27 PM" src="https://user-images.githubusercontent.com/101414331/215191406-00b058de-cce1-4357-bdc3-1b5a5265ba60.png">

And paste, only the first field gets filled
<img width="262" alt="Screenshot 2023-01-27 at 9 33 25 PM" src="https://user-images.githubusercontent.com/101414331/215191548-248a172e-d94b-47c8-99a0-f4d465c6d3e2.png">
The pic below is the expected behaviour after clicking paste
<img width="266" alt="Screenshot 2023-01-27 at 9 34 34 PM" src="https://user-images.githubusercontent.com/101414331/215191710-7fc2f459-c195-4b9c-a311-67575bbd5b95.png">

I hope this can be fixed soon as I am already using the package and don't want to replace it, Thanks

**Comment by benjamineruvieru** [comment]
Please what's the update on this issue. Thanks

**Comment by naveenvignesh5** [comment]
Looking this issue, will be pushing out a release soon @benjamineruvieru.

**Comment by tahahaz1374** [comment]
Any updates on this issue?

**Comment by krishnatheog** [comment]
Does this package support autofill ?

**Comment by olarra** [comment]
hello,  @naveenvignesh5  do you have any updates about this issue?

**Comment by Rananjaya** [comment]
same issue, Does this package support autofill ?

**Comment by alihaider8283** [comment]
same issue

**Comment by alihaider8283** [comment]
any update?

**Comment by Gokul9995** [comment]
@naveenvignesh5 , let me know any step you taken to fix  this issue? From my side i will look into it if time permits. Since it is mostly important . Since due to this issues we cant use this package.

**Comment by naveenvignesh5** [comment]
Latest release contains fix for this. Update **Example** to implement paste scenario. Kindly check.

**Comment by jacquesdev** [comment]
@naveenvignesh5 - interestingly this works perfectly for Android - but it seems to be a bug on iOS (currently).

I've looked at your examples - but it seems I'd still have to load in something like a clipboard plugin to check for text that gets pasted and then sets the value manually as you suggested.

So for what it's worth for others, that's what I'll be doing, adding https://github.com/react-native-clipboard/clipboard, checking for new paste values and setting them in the input

**Comment by naveenvignesh5** [comment]
@jacquesdev let me investigate and get back.

**Comment by shafqatbari** [comment]
https://github.com/naveenvignesh5/react-native-otp-textinput/issues/45#issuecomment-2202099494
Using Clipboard is not a valid solution
