### ISSUE TITLE
I want button so that i can   clear the input value inside it

### ISSUE THREAD

**Issue by rohanthakran** [naveenvignesh5/react-native-otp-textinput#33]
When i am looking at documentation there is a method to clear the value but when I implement is in my code the filed is not clearing

**Comment by mwelwankuta** [comment]
it this still the case

**Comment by naveenvignesh5** [comment]
@rohanthakran could you paste the snippet here ?

**Comment by naveenvignesh5** [comment]
Closing this as the above example will clarify the usage as this is not a bug.
