### ISSUE TITLE
Package outdated

### ISSUE THREAD

**Issue by Ebubechi123** [naveenvignesh5/react-native-otp-textinput#42]
Package does not has the updated version of react native

**Comment by keshav263** [comment]
Did you find any good alternatives to the current package?

**Comment by Ebubechi123** [comment]
Good day.
No, I tried forking the project in order to update the version but couldn't
go through with it. So I had to build from scratch.

**Comment by melkishengue** [comment]
@Ebubechi123  do you know why it is pinned to RN 0.60.0?

**Comment by Ebubechi123** [comment]
I have no idea.

**Comment by naveenvignesh5** [comment]
Will look into it

**Comment by naveenvignesh5** [comment]
Addressed in the latest release. Closing this issue.
