### ISSUE TITLE
Version incompatibility

### ISSUE THREAD

**Issue by SoftwareEngineer01** [naveenvignesh5/react-native-otp-textinput#43]
Hi, I have problems with this package currently I have a react native and expo project, 

"react-native": "0.71.6",
"react-native-otp-textinput": "^1.1.1",

Currently I have to install the packages with :

npm install --legacy-peer-deps

Error:

Running "npm install" in /home/expo/workingdir/build directory.

[stderr] 

npm ERR!

[stderr] 

code ERESOLVE

[stderr] 

npm

[stderr] 

ERR! ERESOLVE could not resolve

[stderr] 

npm ERR!

[stderr] 

npm ERR! While resolving: react-native-otp-textinput@1.1.1

[stderr] 

npm ERR! Found: react-native@0.71.6

I hope you can help me

**Comment by AnkitSinghSengarCygbit** [comment]
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: Ecommerce@0.0.1
npm error Found: react-native@0.74.0
npm error node_modules/react-native
npm error   react-native@"0.74.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react-native@"^0.72.4" from react-native-otp-textinput@1.1.5
npm error node_modules/react-native-otp-textinput
npm error   react-native-otp-textinput@"1.1.5" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
