### ISSUE TITLE
Need to be able to turn off tint border in bottom

### ISSUE THREAD

**Issue by hosenur** [naveenvignesh5/react-native-otp-textinput#44]
The tint border in bottom should be customizable or be turned off

**Comment by oscar-fk** [comment]
I fixed it by setting borderBottomWidth manually. If you just do borderWidth: x, it will not apply to bottom for some reason.

**Comment by naveenvignesh5** [comment]
Closing this issue as @oscar-fk's comment indicates this issue can be resolved by passing style.
