### ISSUE TITLE
Paste from clipboard not working

### ISSUE THREAD

**Issue by hosenur** [naveenvignesh5/react-native-otp-textinput#45]
When trying to paste from clipboard, only the first input gets filled

**Comment by oscar-fk** [comment]
You have to use the clipboard package. There is one for react native, and one for expo, so just use the one that applies. Look at the app code sample here https://github.com/naveenvignesh5/react-native-otp-textinput/blob/master/Example/App.tsx

**Comment by gaffarmalik** [comment]
@hosenur Please did this work for you?
I tried this, but it didn't work

**Comment by AbisheekKumar** [comment]
@gaffarmalik I got it working. In case If you are facing issues follow this implementation. You need to install 
`expo-clipboard` using `npm i expo-clipboard`. With this we can able to paste the OTP. If you want to limit the OTP fields only to numbers you can add regex pattern to `handleCellTextChange ()` function.

```
import OTPTextView from "react-native-otp-textinput";
import * as Clipboard from 'expo-clipboard';

const otpField = ( ) =>{
    let otpinput= useRef(null);
    const [otpInput, setOtpInput] = useState("");

      const handleCellTextChange = async (text, i) => {
              if (i === 0 && Clipboard) {
                const clippedText = await Clipboard.getStringAsync();
                if (clippedText && clippedText.slice(0, 1) === text) {
                      otpinput.current?.setValue(clippedText, true);
                    }
              }
    };

    return(
          <View style={{flex:1}}>
                  <OTPTextView 
                        ref={otpinput}
                        handleTextChange={setOtpInput}
                        handleCellTextChange={handleCellTextChange}
                        inputCount={6}
                        tintColor={"purple"}
                        textInputStyle={{borderRadius:10,borderWidth:3}}
                        containerStyle={{marginBottom:10}}
                        keyboardType="numeric"
                  />
          </View>

    )
};

export default otpField;
```

**Comment by naveenvignesh5** [comment]
Clipboard library is not part of this library. Would want to keep this package modular and not make it heavy. You may want to write custom logic for copy paste which is shown in the example code.

You would be required to use one of the two below packages to achieve copy paste functionality.
https://www.npmjs.com/package/@react-native-clipboard/clipboard
https://www.npmjs.com/package/expo-clipboard

Example already given for the former [here](https://github.com/naveenvignesh5/react-native-otp-textinput/blob/master/Example/App.tsx).

Closing this issue.

**Comment by sudhanshu-busy** [comment]
if i=0 then everytime it is going to paste it when I start writing..also if first digit of otp match to any other copied clipboard text  by chance then it will again gonna fill it.
What is solution?
I want it only paste only on I press paste button

**Comment by shafqatbari** [comment]
Using Clipboard is not a valid solution.
