### ISSUE TITLE
Allow option secureTextEntry

### ISSUE THREAD

**Issue by askynet** [naveenvignesh5/react-native-otp-textinput#47]
Hi,
Do we have any config option to mark up input to * for secureTextEntry?

**Comment by AbdurRobTanvir** [comment]
hi @askynet , 
Did you find any solution on this issue?

**Comment by naveenvignesh5** [comment]
You can pass `secureTextEntry` as prop it will work. Any prop that works for text input will work here.
https://reactnative.dev/docs/textinput#securetextentry

**Comment by AbdurRobTanvir** [comment]
@naveenvignesh5  thanks a lot. 
But I have another question, if we pass secureTextEntry then we get sensitive text but the size of the sensitive text is very small. Do you have any idea how to increase the size of this sensitive text.

**Comment by naveenvignesh5** [comment]
@AbdurRobTanvir increase font size. It will increase dot size. You can toggle font size change based on flag used for secureTextEntry.
