### ISSUE TITLE
Reset OTP

### ISSUE THREAD

**Issue by bijuC1983** [naveenvignesh5/react-native-otp-textinput#8]
Hello,
          How do we reset the otp once an input has been entered.
Eg:- I want to reset all inputs when the user hits Resend button.
Changing the default value does not affect.

Thanks

**Comment by shashank0495** [comment]
I'm also facing same issue not able to reset the value once value has been entered.

**Comment by Pravin-L** [comment]
The same issue for me also

**Comment by naveenvignesh5** [comment]
Hey sorry for the delay. Will release a push soon.

**Comment by naveenvignesh5** [comment]
Feature implemented in the latest release. Closing this issue.
